export type BranchDto = { branchId: number; name: string; location?: string | null };
export type BranchTableDto = {
  tableId: number;
  branchId: number;
  displayTableNumber: number;
  numberOfSeats: number;
  qrCode?: string | null;
  statusCode?: string | null;
  statusName: string;
  isAvailable: boolean;
};
export type BranchTablesResponse = {
  success?: boolean;
  branchName?: string;
  tables?: BranchTableDto[];
  requiresLogin?: boolean;
  loginUrl?: string;
};
export type MenuDishIngredientDto = { name: string; quantity: number; unit?: string | null };
export type MenuDishDto = { dishId: number; name: string; description?: string | null; price: number; image?: string | null; unit?: string | null; isVegetarian: boolean; isDailySpecial: boolean; available: boolean; ingredients?: MenuDishIngredientDto[] | null };
export type MenuCategoryDto = { categoryId: number; categoryName: string; displayOrder: number; dishes: MenuDishDto[] };
export type MenuResponse = { branchId: number; branchName: string; categories: MenuCategoryDto[] };
export type ActiveOrderItemDto = { itemId: number; orderId: number; dishId: number; dishName: string; quantity: number; unitPrice: number; lineTotal: number; note?: string | null; unit?: string | null; image?: string | null; status?: string | null };
export type ActiveOrderResponse = { orderId: number; orderCode?: string | null; tableId?: number | null; statusCode: string; orderStatus: string; subtotal: number; totalItems: number; items: ActiveOrderItemDto[]; diningSessionCode?: string | null; hasActiveDiningSession?: boolean; activeOrderIds?: number[]; hasPendingRound?: boolean; pendingOrderId?: number | null };
export type AddOrderItemPayload = { dishId: number; quantity: number; note?: string | null };
export type CustomerTableContextDto = { tableId: number; branchId: number; branchName?: string | null; tableNumber?: number | null };
export type CustomerSessionUserDto = { customerId: number; username: string; name: string; phoneNumber: string; email?: string | null; loyaltyPoints: number };
export type CustomerSessionDto = { authenticated: boolean; customer?: CustomerSessionUserDto | null; tableContext?: CustomerTableContextDto | null };
export type CustomerDishRecommendationDto = {
  dishId: number;
  name: string;
  description?: string | null;
  price: number;
  image?: string | null;
  unit?: string | null;
  isVegetarian: boolean;
  isDailySpecial: boolean;
  available: boolean;
  ingredients?: MenuDishIngredientDto[] | null;
  categoryId: number;
  categoryName: string;
  reason: string;
};
export type CustomerMenuScreenDto = { tableContext: CustomerTableContextDto; customer?: CustomerSessionUserDto | null; menu: MenuResponse; topDishIds: number[]; recommendations: CustomerDishRecommendationDto[]; currentOrderId: number };
export type CustomerMenuRecommendationsDto = { recommendations: CustomerDishRecommendationDto[] };
export type CustomerDashboardOrderDto = { orderId: number; orderCode?: string | null; orderTime?: string | null; statusCode?: string | null; statusName?: string | null; totalAmount: number; itemCount: number };
export type CustomerProfileDto = { customerId: number; username: string; name: string; phoneNumber: string; email?: string | null; address?: string | null; gender?: string | null; dateOfBirth?: string | null; loyaltyPoints: number };
export type CustomerDashboardDto = { customer: CustomerProfileDto; summary: { totalOrders: number; totalSpent: number; pendingOrders: number; completedOrders: number }; recentOrders: CustomerDashboardOrderDto[] };
export type CustomerOrderHistoryDto = { orderId: number; orderCode?: string | null; orderTime?: string | null; completedTime?: string | null; statusCode?: string | null; orderStatus?: string | null; totalAmount: number; itemCount: number; tableNumber?: string | null; note?: string | null };
export type ReadyDishNotificationDto = { notificationId: number; orderId?: number | null; orderItemId?: number | null; dishName?: string | null; message: string; createdAt: string; status?: string | null };
export type CustomerReadyNotificationsDto = { tableId?: number | null; items: ReadyDishNotificationDto[] };
export type CustomerForgotPasswordResultDto = { message: string; resetToken?: string | null; expiresAt?: string | null; resetPath?: string | null };
export type ApiErrorResponse = { success: false; code: string; message: string; details?: unknown };
export type LoyaltyScanResponse = { success: boolean; message: string; customer?: { name: string; phone: string; currentPoints: number; cardPoints: number } | null };
export type DevResetResponse = { success: true; message: string; nextPath: string };
