//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryDish
    {
        public int CategoryDishID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int MenuCategoryID { get; set; }
        public int DishID { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual MenuCategory MenuCategory { get; set; }
    }
}
