//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishDetails
    {
        public int DishID { get; set; }
        public string DishName { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<bool> IsVegetarian { get; set; }
        public Nullable<bool> IsDailySpecial { get; set; }
        public string CategoryName { get; set; }
        public int CategoryID { get; set; }
    }
}
