//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyCards
    {
        public int CardID { get; set; }
        public Nullable<int> Points { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
