//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableNumbers
    {
        public int TableID { get; set; }
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public Nullable<long> TableNumber { get; set; }
        public int NumberOfSeats { get; set; }
        public string QRCode { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> CurrentOrderID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
